### ISSUE TITLE
关于竞赛测试集的几点疑问

### ISSUE THREAD

**Issue by Hanseltu** [chenruibuaa/racebench#1]
你好，我正在准备参加NASAC2019原型竞赛，对你这个题目比较感兴趣，有以下几个问题想咨询一下，方便的话麻烦回复一下，谢谢~

1 最后给出的测试集中是否含有底层相关的依赖代码？如寄存器操作之类的？还是只是C语言？（我的方案需要用llvm编译源码，想知道是否有底层代码影响编译）

2 如下，我看到racebench.c中有5个task，我在设计方案时是否需要考虑task之间的中断操作（如task2的终端函数也可中断task1），还是只在每个task中考虑其中断处理即可？
```
OSTaskSpawn(0xb003, 10, 0, 0x2000, (FUNCPTR)bench_task1, 0, 0, 0, 0);
OSTaskSpawn(0xb004, 9, 0, 0x2000, (FUNCPTR)bench_task2, 0, 0, 0, 0);
OSTaskSpawn(0xb005, 8, 0, 0x2000, (FUNCPTR)bench_task3, 0, 0, 0, 0);

OSTaskSpawn(0xb006, 7, 0, 0x2000, (FUNCPTR)bench_task4, 0, 0, 0, 0);
OSTaskSpawn(0xb007, 6, 0, 0x2000, (FUNCPTR)bench_task5, 0, 0, 0, 0);
```

以上是我在方案设计时遇到的两个问题，希望得到你的回复~

**Comment by chenruibuaa** [comment]
关于1. 最终的测试集都是标准C，屏蔽了底层相关的依赖，保证工具原型聚焦黑心检测算法。
关于2. 中断和任务的交迭是需要考虑的，一般来讲并不存在哪个中断是属于特定的任务的。
